const CharityOrgs = [
    { value: 'Amaraseela Elders’ Home', label: 'Amaraseela Elders’ Home' },
    { value: 'Angel Foundation', label: 'Angel Foundation' },
    { value: 'Anuradapura Deaf & Blind school Society Ltd', label: 'Anuradapura Deaf & Blind school Society Ltd' },
    { value: 'Appeal for Children Committee of Ceylon', label: 'Appeal for Children Committee of Ceylon' },
    { value: 'Cancer Care Association - Sri Lanka', label: 'Cancer Care Association - Sri Lanka' },
    { value: 'Canadapura Children’s Home', label: 'Canadapura Children’s Home' },
    { value: 'Centre For Handicapped', label: 'Centre For Handicapped' },
    { value: 'Charles & Roslene Fernando Trust', label: 'Charles & Roslene Fernando Trust' },
    { value: 'Children’s Corner Orphanage', label: 'Children’s Corner Orphanage' },
    { value: 'Colombo Friend-in-Need Society', label: 'Colombo Friend-in-Need Society' },
    { value: 'Colombo Young Men’s Buddhist Association', label: 'Colombo Young Men’s Buddhist Association' },
    { value: 'Community Development & Social Services Project of the Church of St. Mary & St. John', label: 'Community Development & Social Services Project of the Church of St. Mary & St. John' },
    { value: 'Dev Suwa Sevawa', label: 'Dev Suwa Sevawa' },
    { value: 'Don Bosco Boy’s Home', label: 'Don Bosco Boy’s Home' },
    { value: 'Don Bosco Trust', label: 'Don Bosco Trust' },
    { value: 'Ethanamadala Sahana Elders Home', label: 'Ethanamadala Sahana Elders Home' },
    { value: 'FRIDSRO Children\'s Home', label: 'FRIDSRO Children\'s Home' },
    { value: 'Friends of Marscri', label: 'Friends of Marscri' },
    { value: 'Galkissa Buddha Samithiya', label: 'Galkissa Buddha Samithiya' },
    { value: 'Gamsiri Uda Samithiya Limited', label: 'Gamsiri Uda Samithiya Limited' },
    { value: 'Hanwella Social Services Society, Sende Sarana Elders Home', label: 'Hanwella Social Services Society, Sende Sarana Elders Home' },
    { value: 'HelpAge Sri Lanka', label: 'HelpAge Sri Lanka' },
    { value: 'Hindu Bord of Education', label: 'Hindu Bord of Education' },
    { value: 'Hindu Women’s Society Limited Colombo', label: 'Hindu Women’s Society Limited Colombo' },
    { value: 'Isha Athul Islam Home for the Orphans', label: 'Isha Athul Islam Home for the Orphans' },
    { value: 'Jagaddala Social Welfare Institute', label: 'Jagaddala Social Welfare Institute' },
    { value: 'Kalutara Bodhi Trust', label: 'Kalutara Bodhi Trust' },
    { value: 'Kaluthara Buddhist society', label: 'Kaluthara Buddhist society' },
    { value: 'Kanadarawa Thapowana Vihara Building Fund', label: 'Kanadarawa Thapowana Vihara Building Fund' },
    { value: 'Kandy Buddhist Women Society Jajawickrema Lama Nivasa', label: 'Kandy Buddhist Women Society Jajawickrema Lama Nivasa' },
    { value: 'Kandy Friend-in-need society', label: 'Kandy Friend-in-need society' },
    { value: 'Little Sisters of the Poor', label: 'Little Sisters of the Poor' },
    { value: 'Lotus Hill Home for Disabled Children', label: 'Lotus Hill Home for Disabled Children' },
    { value: 'Maha Mahinda Dharmaduta Special Fund', label: 'Maha Mahinda Dharmaduta Special Fund' },
    { value: 'Mahabodhi Society of Ceylon', label: 'Mahabodhi Society of Ceylon' },
    { value: 'Mallika Nivasa Samithiya (Society) Limited', label: 'Mallika Nivasa Samithiya (Society) Limited' },
    { value: 'Matara Bauddha Kantha Samithiya', label: 'Matara Bauddha Kantha Samithiya' },
    { value: 'Matugama Social Services Society Ltd', label: 'Matugama Social Services Society Ltd' },
    { value: 'Methodist Trust Association of Ceylon', label: 'Methodist Trust Association of Ceylon' },
    { value: 'Moors” Islamic Cultural Home', label: 'Moors” Islamic Cultural Home' },
    { value: 'Moratuwa Social Service Society (Elders Home)', label: 'Moratuwa Social Service Society (Elders Home)' },
    { value: 'Morawinna Girls home', label: 'Morawinna Girls home' },
    { value: 'Muslim Ladies Arabic College Managing Society', label: 'Muslim Ladies Arabic College Managing Society' },
    { value: 'Norman Weerasooria Memorial Shelter', label: 'Norman Weerasooria Memorial Shelter' },
    { value: 'Obesekara Elders Home', label: 'Obesekara Elders Home' },
    { value: 'Panadura Child Welfare & social Service League', label: 'Panadura Child Welfare & social Service League' },
    { value: 'Peter Weerasekera Foundation', label: 'Peter Weerasekera Foundation' },
    { value: 'Pihimbiyahena Elder’s Home', label: 'Pihimbiyahena Elder’s Home' },
    { value: 'Piliyandala Young Men’s Buddhist Association', label: 'Piliyandala Young Men’s Buddhist Association' },
    { value: 'Pradeepaloka Buddhist Balika Home', label: 'Pradeepaloka Buddhist Balika Home' },
    { value: 'Prithipura Infants Home', label: 'Prithipura Infants Home' },
    { value: 'Ramakrishna Sarada Mission', label: 'Ramakrishna Sarada Mission' },
    { value: 'Rohana (blind, deaf) Special School and Hostel', label: 'Rohana (blind, deaf) Special School and Hostel' },
    { value: 'SOS Children’s Villages Sri Lanka', label: 'SOS Children’s Villages Sri Lanka' },
    { value: 'Sahanoda Elders Home', label: 'Sahanoda Elders Home' },
    { value: 'Samastha Lanka Wakugadu Roginge Sangamaya', label: 'Samastha Lanka Wakugadu Roginge Sangamaya' },
    { value: 'Sarana Nikethanaya', label: 'Sarana Nikethanaya' },
    { value: 'Sarana Women’s Elderly Home', label: 'Sarana Women’s Elderly Home' },
    { value: 'Saviya Development Foundation', label: 'Saviya Development Foundation' },
    { value: 'Seemasahitha Matara, Arogya Seva Samithiya', label: 'Seemasahitha Matara, Arogya Seva Samithiya' },
    { value: 'Seemasahitha Sarvodaya Suwasetha Seva Samithiya', label: 'Seemasahitha Sarvodaya Suwasetha Seva Samithiya' },
    { value: 'Shanthi Nivasa', label: 'Shanthi Nivasa' },
    { value: 'Shilpa Children’s Trust', label: 'Shilpa Children’s Trust' },
    { value: 'Shri Senarath Gunawardana Children’s Development Centre', label: 'Shri Senarath Gunawardana Children’s Development Centre' },
    { value: 'Sisters of Charity of Jesus and Mary', label: 'Sisters of Charity of Jesus and Mary' },
    { value: 'Special Educational Service Society', label: 'Special Educational Service Society' },
    { value: 'Sri Lanka Cancer Society', label: 'Sri Lanka Cancer Society' },
    { value: 'Sri Lanka Technical Institute & Diyagala Boy’s town', label: 'Sri Lanka Technical Institute & Diyagala Boy’s town' },
    { value: 'Sri Lankadhara Society Limited', label: 'Sri Lankadhara Society Limited' },
    { value: 'Sri Mahinda Dharmaduta Samithiya', label: 'Sri Mahinda Dharmaduta Samithiya' },
    { value: 'Sri Paramananda Children’s & Elder’s Home', label: 'Sri Paramananda Children’s & Elder’s Home' },
    { value: 'Sri Punyawardhana Samithiya', label: 'Sri Punyawardhana Samithiya' },
    { value: 'Sri Sucharithadhara Upasika Samithiya Ltd', label: 'Sri Sucharithadhara Upasika Samithiya Ltd' },
    { value: 'St. Joseph’s Educational Foundation for the Hearing Impaired', label: 'St. Joseph’s Educational Foundation for the Hearing Impaired' },
    { value: 'St/ Margaret Home', label: 'St/ Margaret Home' },
    { value: 'Sudaya Trust', label: 'Sudaya Trust' },
    { value: 'Siyane Korale East – Social Service League', label: 'Siyane Korale East – Social Service League' },
    { value: 'The Brave Hearts Fund of the Seva Vanitha Army Unit', label: 'The Brave Hearts Fund of the Seva Vanitha Army Unit' },
    { value: 'The Ceylon Moor Ladies Union', label: 'The Ceylon Moor Ladies Union' },
    { value: 'The Ceylon School For the Deaf and Blind', label: 'The Ceylon School For the Deaf and Blind' },
    { value: 'The King George the fifth Silver Jubilee Commemoration society', label: 'The King George the fifth Silver Jubilee Commemoration society' },
    { value: 'The Oblates of Mary Immaculata Province of Sri Lanka', label: 'The Oblates of Mary Immaculata Province of Sri Lanka' },
    { value: 'The Paynter Home For Children', label: 'The Paynter Home For Children' },
    { value: 'Udaya Children’s home', label: 'Udaya Children’s home' },
    { value: 'YMBA Maharagama', label: 'YMBA Maharagama' },
    { value: 'Other', label: 'Other' },
];
export default CharityOrgs;